### ISSUE TITLE
2017-05-30 Representatives debates missing

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#1160]
You can see the gap here: http://www.openaustralia.org.au/debates/?y=2017

Here's the day on APH.gov.au: http://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Date%3A30%2F5%2F2017;rec=0;resCount=Default

**Comment by henare** [comment]
Here's the exception thrown on the day:

```
 ./../openaustralia-parser/lib/hansard_parser.rb:77:in `unpatched_hansard_xml_source_data_on_date': undefined method `body' for #<PageProxy:0xb60d3278> (NoMethodError)
        from ../../openaustralia-parser/lib/hansard_parser.rb:85:in `hansard_xml_source_data_on_date'
        from ../../openaustralia-parser/lib/hansard_parser.rb:117:in `hansard_day_on_date'
        from ../../openaustralia-parser/lib/hansard_parser.rb:155:in `parse_date_house'
        from ../../openaustralia-parser/parse-speeches.rb:88
```

Locally I get something different:

```
henare@mana:/var/www/openaustralia/openaustralia-parser rvm:(ruby-1.8.7-p370) git:(master)$ ./parse-speeches.rb 2017-05-30
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.9.1
/home/henare/.rvm/gems/ruby-1.8.7-p370/gems/htmlentities-4.3.4/lib/htmlentities/encoder.rb:25:in `prepare': uninitialized constant HTMLEntities::Encoder::Encoding (NameError)
	from /home/henare/.rvm/gems/ruby-1.8.7-p370/gems/htmlentities-4.3.4/lib/htmlentities/encoder.rb:19:in `encode'
	from /home/henare/.rvm/gems/ruby-1.8.7-p370/gems/htmlentities-4.3.4/lib/htmlentities.rb:73:in `encode'
	from ./lib/speech.rb:40:in `append_to_content'
	from /home/henare/.rvm/gems/ruby-1.8.7-p370/gems/hpricot-0.6.164/lib/hpricot/traverse.rb:693:in `traverse_text_internal'
	from /home/henare/.rvm/gems/ruby-1.8.7-p370/gems/hpricot-0.6.164/lib/hpricot/traverse.rb:682:in `traverse_text_internal'
	from /home/henare/.rvm/gems/ruby-1.8.7-p370/gems/hpricot-0.6.164/lib/hpricot/traverse.rb:492:in `each'
	from /home/henare/.rvm/gems/ruby-1.8.7-p370/gems/hpricot-0.6.164/lib/hpricot/traverse.rb:492:in `each_child'
	from /home/henare/.rvm/gems/ruby-1.8.7-p370/gems/hpricot-0.6.164/lib/hpricot/traverse.rb:682:in `traverse_text_internal'
	from /home/henare/.rvm/gems/ruby-1.8.7-p370/gems/hpricot-0.6.164/lib/hpricot/traverse.rb:682:in `traverse_text_internal'
	from /home/henare/.rvm/gems/ruby-1.8.7-p370/gems/hpricot-0.6.164/lib/hpricot/traverse.rb:492:in `each'
	from /home/henare/.rvm/gems/ruby-1.8.7-p370/gems/hpricot-0.6.164/lib/hpricot/traverse.rb:492:in `each_child'
	from /home/henare/.rvm/gems/ruby-1.8.7-p370/gems/hpricot-0.6.164/lib/hpricot/traverse.rb:682:in `traverse_text_internal'
	from /home/henare/.rvm/gems/ruby-1.8.7-p370/gems/hpricot-0.6.164/lib/hpricot/traverse.rb:674:in `traverse_text'
	from ./lib/speech.rb:39:in `append_to_content'
	from ./lib/debates.rb:69:in `add_speech'
	from ./lib/hansard_parser.rb:177:in `parse_date_house'
	from ./lib/hansard_parser.rb:170:in `each'
	from ./lib/hansard_parser.rb:170:in `parse_date_house'
	from ./lib/hansard_parser.rb:159:in `each'
	from ./lib/hansard_parser.rb:159:in `parse_date_house'
	from ./parse-speeches.rb:88
```

Running it with bundle exec works though:

```
henare@mana:/var/www/openaustralia/openaustralia-parser rvm:(ruby-1.8.7-p370) git:(master)$ be ./parse-speeches.rb 2017-05-30
parse-speeche: 100% |oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:11
db loading  2017-05-30
henare@mana:/var/www/openaustralia/openaustralia-parser rvm:(ruby-1.8.7-p370) git:(master)$ 
```

**Comment by henare** [comment]
I suspected that maybe the original exception thrown on the day was due to malformed data from APH. Deleting the cache and reparsing proved this correct:

```
deploy@kedumba:/srv/www/www.openaustralia.org/current/openaustralia-parser$ rm -r /srv/www/www.openaustralia.org/shared/html_cache/2017-05-30
deploy@kedumba:/srv/www/www.openaustralia.org/current/openaustralia-parser$ ./parse-speeches.rb 2017.05.30                                                              [DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
WARNING: Nokogiri was built against LibXML version 2.7.6, but has dynamically loaded 2.7.8
parse-speeche: 100% |oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:14
db loading  2017-05-30
deploy@kedumba:/srv/www/www.openaustralia.org/current/openaustralia-parser$
```

I also noticed another day missing, 2017-02-28, and this was due to missing upstream data:

```
deploy@kedumba:/srv/www/www.openaustralia.org/current/openaustralia-parser$ ./parse-speeches.rb 2017.02.28
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
WARNING: Nokogiri was built against LibXML version 2.7.6, but has dynamically loaded 2.7.8
parse-speeche: 100% |oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:00
deploy@kedumba:/srv/www/www.openaustralia.org/current/openaustralia-parser$ rm -r /srv/www/www.openaustralia.org/shared/html_cache/2017-02-28
deploy@kedumba:/srv/www/www.openaustralia.org/current/openaustralia-parser$ ./parse-speeches.rb 2017.02.28
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
WARNING: Nokogiri was built against LibXML version 2.7.6, but has dynamically loaded 2.7.8
parse-speeche: 100% |oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:14
db loading  2017-02-28
deploy@kedumba:/srv/www/www.openaustralia.org/current/openaustralia-parser$
```

**Comment by henare** [comment]
Also did this: https://github.com/openaustralia/openaustralia/wiki/Email-alert-tasks#skipping-email-alerts

And loaded this into TVFY:

```
deploy@kedumba:/srv/www/www.openaustralia.org/current/openaustralia-parser$ cd /srv/www/theyvoteforyou.org.au/current/ && /home/deploy/.rvm/wrappers/ruby-2.3.1/ruby bin/rake application:load:divisions[2017-02-28] RAILS_ENV=production
Division reload mismatch! representatives 2017-02-28: 0 divisions in the database and 1 in the XML
Saving division: representatives 2017-02-28 1
No XML file found for senate on 2017-02-28 at http://data.openaustralia.org.au/scrapedxml/senate_debates/2017-02-28.xml
deploy@kedumba:/srv/www/theyvoteforyou.org.au/current$ cd /srv/www/theyvoteforyou.org.au/current/ && /home/deploy/.rvm/wrappers/ruby-2.3.1/ruby bin/rake application:load:divisions[2017-05-30] RAILS_ENV=production
No debates found in XML for representatives on 2017-05-30
No XML file found for senate on 2017-05-30 at http://data.openaustralia.org.au/scrapedxml/senate_debates/2017-05-30.xml
deploy@kedumba:/srv/www/theyvoteforyou.org.au/current$ cd /srv/www/theyvoteforyou.org.au/current/ && /home/deploy/.rvm/wrappers/ruby-2.3.1/ruby bin/rake application:cache:all_except_member_distances RAILS_ENV=production
Updating cache of guessed whips...
[left running in screen for ages]
```
